### ISSUE TITLE
다른 (좀 더 빠르게 업데이트되는) 데이터 소스?

### ISSUE THREAD

**Issue by hanbyul-here** [hanbyul-here/seoul-metro-turnstile-data#11]
[기사들](http://news.heraldcorp.com/view.php?ud=20161211000095)을 읽어보면 뭔가 좀 더 빠르게 데이터에 접근하는 방법이 있는 것 같은데 혹시 아시는 분 있으면 제보해주세요!!!

**Comment by graynun** [comment]
조금 찾아보고 있는데 11월 13일에는 [이런 보도자료](http://spp.seoul.go.kr/main/news/news_report.jsp?searchType=TITLE&searchWord=%B1%A4%C8%AD%B9%AE&list_start_date=&list_end_date=&pageSize=10&branch_id=&branch_child_id=&pageNum=1&communityKey=B0158&boardId=29561&act=VIEW)를 통해서 hwp로 뿌리고(근데 맥에서는 exe파일만 받아져서 못열어봤습니다...), 그 이후에도 비슷한 방식으로 계속 뿌리는 것 같은데 보도자료 게시판에 없네요...

**Comment by hanbyul-here** [comment]
헉 이런 보도자료를 찾아내다니 @graynun 너무나 능력자! 

지금 보도자료 열어서 몇몇 역의 하차인원 확인해보고있는데 왜 이 보도자료의 숫자랑 오픈데이터포털에서 가져온 숫자가  맞아떨어지지 않는 걸까요. 

예시) 11월 12일 광화문 하차 승객수 111271 ( 오픈데이터포털) 111146 (보도자료)

헉 데이터 처리를 잘못하고 있나!해서 [데이터 소스 확인해보니](http://openapi.seoul.go.kr:8088/7769736378776f6e33396e4f644142/json/CardSubwayStatsNew/1/600/20161112) 데이터는 맞게 모이고있는 것 같은데 뭔가 집계 컷라인이 다른가 싶기도 하고 (이를테면 보도자료는 자정까지컷해서 내고 데이터포털에는 막차시간까지 합해서 올린다던가..? 저의 추측입니다.)

미스테리만 느네요.. 한글 파일 열기 어려운 분들을 위해 보도자료 중 집계 테이블만 스크린샷 첨부합니다.

<img width="902" alt="screen shot 2016-12-18 at 12 07 29 am" src="https://cloud.githubusercontent.com/assets/4583806/21291679/ece11946-c4b6-11e6-991b-591f5084dd3a.png">

**Comment by graynun** [comment]
근데 저희는 사실 보도자료에 쓰인 것과 서울시 데이터광장에서 제공하는 데이터가 어떻게 다른지 알기 힘든것이 문제네요...
게다가 아예 숫자가 다르면 뭐지 둘중에 하나는 잘못되었다! 이럴텐데 막 크게 차이가 나는 것도 아니고 매우 미묘하게 차이나고 말이죠...
아무래도 시간이 명시되어 있지 않으니 @hanbyul-here 님이 말씀하신대로 시간대 차이(00시에서 끊는다 vs 막차까지 넣는다)가 조금 유력할 것 같은데....이것도 검색해 보면 나올까요?

**Comment by hanbyul-here** [comment]
서울시쪽에 이메일을 보내는 게 가장 정확한 답변을 얻는 일일테지만 페이지에 나와있는 번호로 전화... 를 하기엔 정말 너무 수줍네요... 우선 이 이슈와 직접적으로 관계되는 건 아닌 듯 하니 닫겠습니다.
